export const categoriesList = [
    'Different products types',
    'Rims',
    'Body kits',
    'Bullbar',
    'Front splinter',
    'Interior upgrade',
    'Infotainment system',
    'Sound system',
    'Spoiler',
    'Floor mats',
    'Front splinter',
    'Rear splinter',
    'Seat leather',
    'Head Lights',
    'Rear lights',
    'Bed cover',
    'Bed liner',
    'Snorkel',
    'Shock absorbers',
    'Fog lights',
    'Side steps',
    'Springs',
    'Light bars',
    'Exhaust',
    'Exhaust tips',
    'Roll bar',
    'Safety guard',
    'Skid plates',
    'Scuff plates',
    'Canopy',
    'Wheel cover',
    'Roof rack',
    'Mirror cover',
    'Fender flares',
    'Hook',
    'Off road accessories',
    'Electric car accessories',
    'Electric car chargers',
    'Speedometer',
    'Grill',
    'Power window',
    'Switches',
    'Hood',
    'Mud flaps',
    'Fog light cover',
    'Moulding',
    'Electric tailgate',
    'Electric seats',
    'VIP seats',
    'Roof tent',
    'Steering wheel',
    'Front bumper',
    'Rear bumper',
]